name: build-mynote
on: push

jobs:
  build-mynote:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt install python-pip openssh-server sshpass -y
        sudo pip install mkdocs mkdocs-rtd-dropdown
    - uses: actions/checkout@master
    - run: ls -al
    - run: mkdocs build
    - name: push server
      run: |
        ls -al
        sshpass -p chlish520 scp -r -P 5821 site/* root@note.mzcls.com:/var/www/mynote/

