name: build-mynote
on: push

jobs:
  build-mynote:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt install python-pip openssh-server -y
        sudo pip install mkdocs mkdocs-ivory
    - uses: actions/checkout@master
    - run: ls -al
    - run: mkdocs build
    - name: push server
      run: |
        mkdir ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600  ~/.ssh/id_rsa
        ssh-keyscan -p 5821 note.mzcls.com > ~/.ssh/known_hosts
        scp -r -P 5821 site/* root@note.mzcls.com:/var/www/mynote/
      env:
        SSH_KEY: ${{secrets.SSH_KEY}}
